# Generated by Django 4.2.1 on 2023-12-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Correos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="undercontractbuyer",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Closed", "Closed")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
