# Generated by Django 4.2.1 on 2023-12-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Correos", "0002_undercontractbuyer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="undercontractbuyer",
            name="other_agent_email",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Agent's Email"
            ),
        ),
    ]
