# Generated by Django 4.2.1 on 2023-12-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembers",
            name="closed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teammembers",
            name="pending",
            field=models.IntegerField(default=0),
        ),
    ]
