# Generated by Django 4.2.1 on 2023-12-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Team", "0003_alter_teammembers_closed_alter_teammembers_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembers",
            name="closed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teammembers",
            name="pending",
            field=models.IntegerField(default=0),
        ),
    ]
